# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c91508f6f9b169c96b5e667dcd38833f0dbd48f09be0662b1f31a03aadf75142f72165519d0552d5f098b92fb6d56d4de4cd273b4a0604cfbf9d6363510f4706

test:
  secret_key_base: 828132e246e92d221ac2191ab21d7ad6440dfce1ccd5494c52cfbe9c9cb32f2be74901bdcecf99378aaeeb68cd955c5ea6f9c0f3631a2d53c139e79b332d3d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ba1ea20b0aee0b403c7ea89cf2978463689ccae039dfe35e350773495565274940b1ee4cc0968ae72ebc713c4f99f22548d6ec243d4fd3562e28f32ab34852d0